In [ ]:
Exercise 2

In [ ]:
 Problem Statement

The function swap() is intended to swap x and y coordinates in a bounding box array. However, the returned coordinates are incorrect.

In [2]:
import csv
import numpy as np
from typing import Set,Tuple, List
import torch
import torch.utils
import torch.utils.data
import torch.nn as nn
import torchvision
NoneType = type(None)
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
from PIL import Image
import torchvision.transforms.functional as TF
from torchvision.models import vgg11
from torchvision.models import mobilenet_v2
import torchvision.transforms as transforms
import time

In [ ]:
 Bug Analysis

coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3] = \
coords[:, 1], coords[:, 1], coords[:, 3], coords[:, 2]
The value coords[:,1] is assigned twice, causing the original x-coordinate values to be lost.

In [3]:
def swap(coords: np.ndarray):
    """
    ...same docstring...
    """
    new_coords = coords.copy()          
    new_coords[:, 0] = coords[:, 1]     
    new_coords[:, 1] = coords[:, 0]     
    new_coords[:, 2] = coords[:, 3]     
    new_coords[:, 3] = coords[:, 2]    
    return new_coords

coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5,  3, 13, 6, 1],
                   [4,  4, 13, 6, 1],
                   [6,  5, 13, 16, 1]])

swapped_coords = swap(coords)
print(swapped_coords)

[[ 5 10  6 15  0]
 [ 3 11  6 13  0]
 [ 3  5  6 13  1]
 [ 4  4  6 13  1]
 [ 5  6 16 13  1]]


In [ ]:
 Conclusion

The bug was caused by an incorrect assignment statement and unsafe in-place modification of NumPy arrays. Creating a copy of the data before swapping prevents overwriting and ensures correct coordinate transformation.